# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  DEV: nix develop .#default -c
  PROF: nix develop .#profiling -c
  PROFILE_DIR: profiling

tasks:
  build:
    desc: Configure and build
    cmds:
      - "{{.DEV}} cmake -S . -B build -G Ninja"
      - "{{.DEV}} cmake --build build"

  test:
    desc: Build and run test suite with ctest
    deps:
      - build
    cmds:
      - "{{.DEV}} ctest --test-dir build --output-on-failure"

  clean:
    desc: Remove the CMake build directory
    cmds:
      - "{{.DEV}} rm -rf build"

  clangd:
    desc: Regenerate clangd config
    cmds:
      - "{{.DEV}} nix run .#generate-clangd"

  axpy:
    desc: Build and run the AXPY example
    deps:
      - build
    cmds:
      - "{{.DEV}} cmake --build build --target axpy_example"
      - "{{.DEV}} ./build/axpy_example"

  train-linear:
    desc: Build and run the linear training demo
    deps:
      - build
    cmds:
      - "{{.DEV}} cmake --build build --target train_linear"
      - "{{.DEV}} ./build/train_linear {{.CLI_ARGS}}"

  profile-nsys:
    desc: Profile train_linear with Nsight Systems (output in profiling/)
    deps:
      - build
    cmds:
      - "mkdir -p {{.PROFILE_DIR}}"
      - "{{.PROF}} bash -lc 'set -euo pipefail; timeout 180s nsys profile -t cuda,nvtx,osrt --stats=true -o {{.PROFILE_DIR}}/nsys_train_linear --force-overwrite true ./build/train_linear {{.CLI_ARGS}}'"

  profile-ncu:
    desc: Profile train_linear with Nsight Compute (output in profiling/)
    deps:
      - build
    cmds:
      - "mkdir -p {{.PROFILE_DIR}}"
      - "{{.PROF}} bash -lc 'set -euo pipefail; export HOME=/tmp/pkt_ncu_home; mkdir -p \"$HOME\"; NCU_BIN=\"$(readlink -f \"$(command -v ncu)\")\"; NCU_ROOT=\"$(dirname \"$(dirname \"$NCU_BIN\")\")\"; SECTIONS=\"$NCU_ROOT/sections\"; timeout 120s ncu --config-file 0 --section-folder-recursive \"$SECTIONS\" --set full -k persistent_kernel --launch-count 1 --target-processes all -f --page details --print-details all -o {{.PROFILE_DIR}}/ncu_train_linear ./build/train_linear {{.CLI_ARGS}}'"

  profile-ncu-basic:
    desc: Quick NCU (basic set) on persistent_kernel (output in profiling/)
    deps:
      - build
    cmds:
      - "mkdir -p {{.PROFILE_DIR}}"
      - "{{.PROF}} bash -lc 'set -euo pipefail; export HOME=/tmp/pkt_ncu_home; mkdir -p \"$HOME\"; NCU_BIN=\"$(readlink -f \"$(command -v ncu)\")\"; NCU_ROOT=\"$(dirname \"$(dirname \"$NCU_BIN\")\")\"; SECTIONS=\"$NCU_ROOT/sections\"; timeout 600s ncu --config-file 0 --section-folder-recursive \"$SECTIONS\" --set basic -k persistent_kernel --launch-count 1 --target-processes all -f --page details --print-details all -o {{.PROFILE_DIR}}/ncu_train_linear_basic ./build/train_linear {{.CLI_ARGS}}'"
